export const theme = {
  fonts: {
    body: "'Rubik', sans-serif",
    display: "'Secular One', sans-serif",
  },
  radius: {
    pill: "100px",
    card: "28px",
    cardLarge: "32px",
    section: "36px",
    input: "17px",
  },
  background: {
    page: "#FDFDF9",
    card: "#FFFFFF",
    tint: "#F2FBF6",
    tintSoft: "#F8FCF9",
    fill: "#F5F3E8",
    fillHover: "#EDEADB",
    dashed: "#FBF9F0",
    lightGray: "#F6F8FB",
  },
  colors: {
    info: "#1D2B4F",
    error: "#DE4040",
    white: "#FFFFFF",
    black: "#1D2B4F",
    ink: "#1D2B4F",
    muted: "#6B7699",
    mutedLight: "#9AA3BC",
    disabled: "#C3C8D6",
    warning: "#DB7C22",
    success: "#28C76F",
    green: "#28C76F",
    greenDark: "#1E9E55",
    greenDarker: "#158B47",
    greenLight: "#2FD97B",
    greenTint: "#F2FBF6",
    greenTintBorder: "#BFE8CF",
    greenDisabled: "#BFE8CF",
    greenDisabledShadow: "#A8D8BB",
    orange: "#FF9F43",
    orangeDark: "#DB7C22",
    orangeLight: "#FFAE5E",
    orangeTint: "#F6D3AC",
    orangeTintSoft: "#FFF6EC",
    orangeTintSoftHover: "#FFEFDD",
    orangeTintShadow: "#F0DCC4",
    gold: "#FFC300",
    goldDark: "#D9A500",
    goldTint: "#FFD968",
    goldTintSoft: "#FFFBEC",
    goldTintBorder: "#F5E1A4",
    goldTintShadow: "#F0E3BE",
    greenTintShadow: "#D3EEDF",
  },
  button: {
    primary: "#28C76F",
    secondary: "#F2FBF6",
  },
  border: {
    primary: "#1D2B4F",
    natural: "#E4E1D2",
    subtle: "#F3F1E7",
    faint: "#EFEDE2",
    tintSoft: "#DDEFE4",
  },
  shadow: {
    default: "#EDEBE0",
    card: "0 6px 0 #EDEBE0, 0 18px 40px rgba(29,43,79,.06)",
    cardTint: "0 6px 0 #CDEEDB",
    cardTintElevated: "0 10px 0 #CDEEDB, 0 22px 38px rgba(29,43,79,.14)",
    secondary:
      "inset 0 0 0 1px rgba(16,22,26,.2), inset 0 -1px 0 rgba(16,22,26,.1)",
  },
  severity: {
    info: "#9AA3BC",
    warning: "#DB7C22",
    error: "#DE4040",
  },
  text: {
    textfield: {
      default: "#1D2B4F",
      disabled: "#C3C8D6",
    },
  },
  tabBar: {
    track: "#EFEBDB",
    inactiveText: "#8D95AC",
  },
} as const;

export const TONE_STYLES = {
  warning: {
    background: theme.colors.orangeTintSoft,
    border: theme.colors.orangeTint,
    shadow: `0 4px 0 ${theme.colors.orangeTintShadow}`,
  },
  win: {
    background: theme.background.tint,
    border: theme.colors.greenTintBorder,
    shadow: `0 4px 0 ${theme.colors.greenTintShadow}`,
  },
  streak: {
    background: theme.colors.goldTintSoft,
    border: theme.colors.goldTintBorder,
    shadow: `0 4px 0 ${theme.colors.goldTintShadow}`,
  },
} as const;
