import { createStyles } from "../../../create-styles";
import { theme } from "../../../constants/theme.constants";

export const useStyles = () =>
  createStyles({
    card: {
      gap: 8,
      display: "flex",
      minHeight: 282,
      textAlign: "center" as const,
      alignItems: "center",
      padding: "26px 22px",
      justifyContent: "center",
      boxSizing: "border-box" as const,
      flexDirection: "column" as const,
      border: `2px dashed ${theme.border.natural}`,
    },
    icon: {
      width: 62,
      height: 62,
      display: "block",
    },
    title: {
      fontSize: 21,
      color: theme.colors.ink,
      fontFamily: theme.fonts.display,
    },
    description: {
      fontSize: 15,
      lineHeight: 1.5,
      color: theme.colors.muted,
      fontFamily: theme.fonts.body,
    },
    button: {
      marginTop: 10,
    },
    hiddenInput: {
      display: "none",
    },
    uploadedCard: {
      gap: 18,
      display: "flex",
      minHeight: 282,
      padding: "20px 18px",
      justifyContent: "center",
      boxSizing: "border-box" as const,
      flexDirection: "column" as const,
    },
    filePreview: {
      gap: 12,
      display: "flex",
      alignItems: "center",
      borderRadius: 22,
      padding: "12px 14px",
      backgroundColor: theme.background.tintSoft,
      border: `2px solid ${theme.border.tintSoft}`,
    },
    fileIcon: {
      width: 38,
      height: 38,
      display: "block",
      flex: "0 0 auto",
    },
    fileText: {
      flex: 1,
      minWidth: 0,
      display: "flex",
      gap: 3,
      flexDirection: "column" as const,
    },
    fileName: {
      fontSize: 15,
      fontWeight: 700,
      lineHeight: 1.3,
      direction: "ltr" as const,
      textAlign: "right" as const,
      whiteSpace: "nowrap" as const,
      overflow: "hidden" as const,
      textOverflow: "ellipsis" as const,
      color: theme.colors.ink,
      fontFamily: theme.fonts.body,
    },
    fileMeta: {
      fontSize: 13,
      color: theme.colors.muted,
      fontFamily: theme.fonts.body,
    },
    removeButton: {
      width: 34,
      height: 34,
      flex: "0 0 auto",
      color: theme.colors.muted,
      backgroundColor: theme.colors.white,
      border: `2px solid ${theme.border.natural}`,
      boxShadow: `0 3px 0 ${theme.border.natural}`,
      "&:hover": {
        color: theme.colors.orangeDark,
        borderColor: theme.colors.orange,
        backgroundColor: theme.colors.white,
        boxShadow: `0 3px 0 ${theme.colors.orangeTint}`,
      },
      "&:active": {
        transform: "translateY(3px)",
        boxShadow: `0 0 0 ${theme.colors.orangeTint}`,
      },
    },
    removeGlyph: {
      fontSize: 16,
      fontWeight: 800,
      lineHeight: 1,
    },
    uploadButton: {
      width: "100%",
      padding: "15px 24px",
    },
    privacyNote: {
      gap: 6,
      display: "flex",
      fontSize: 13,
      alignItems: "center",
      justifyContent: "center",
      color: theme.colors.muted,
      fontFamily: theme.fonts.body,
    },
    lockIcon: {
      width: 16,
      height: 16,
      display: "block",
    },
  });
